@api = http://localhost:3000/orders
@apiT = http://localhost:3000/tables

@apiD = http://localhost:3000/dishes

@apiE = http://localhost:3000/extras

@apiL = http://localhost:3000/login

### Get all orders
{{api}}

### create a new order
POST {{api}}
Content-Type: application/json

{"table":"1002","user":"1","extras":[1],"dishes":[1],"note":"Gare"}

### get a single order
{{api}}/1

### delete a single order
DELETE {{api}}/1003

### update order
PUT {{api}}/5
Content-Type: application/json

{
}